### ISSUE TITLE
Build a shitty website as inspiration for attendees

### ISSUE THREAD

**Issue by nicokoenig** [nicokoenig/newdevsontheblock#16]
- [ ] Sara made a neat website

- [ ] Klara made a fancy website

- [ ] Martin made a fantastic website 

- [ ] Carolyn made a nifty website

- [ ] Nico made a decent website

**Comment by miffili** [comment]
What? Fancy? 🤔
What does that even mean?

**Comment by nicokoenig** [comment]
@Miffili this was one outcome of the talk, to build a really small website (header, nav, main, footer) with a random topic (cupcakes, football, horses, whatever) as an inspiration for the workshop (and as a reference)
